### ISSUE TITLE
Automatic translations

### ISSUE THREAD

**Issue by solarkraft** [stevenliatti/doc-tagfs#1]
Hi, I recently became interested in this topic again and found your project by literally searching "inotify xattrs" - looks like we had the same idea :-)

Thanks a lot for publishing your work! For myself and everyone playing along at home who doesn't know french I ran the PDFs through Google Translate, maybe it'll be useful for someone. 

[tagfs-pres-en.pdf](https://github.com/stevenliatti/doc-tagfs/files/10365236/tagfs-pres-en.pdf)
[tagfs-report-en.pdf](https://github.com/stevenliatti/doc-tagfs/files/10365237/tagfs-report-en.pdf)

**Comment by stevenliatti** [comment]
Hello, thank you for your interest and translation ! At that time, I was focus on the content and the code production and was not enough confident to entirely write my bachelor thesis in English ;-)

I will add the translated docs in repository :+1: (b67bd25474d9d2f0b320946ac5158066615cc52f)
